#!/usr/bin/env node
/**
 * Build the search index from the site's own content.
 *
 *   node scripts/build-search.mjs
 *
 * Two sources, deliberately: the pages (headings and prose, so a visitor can
 * find "what went wrong" or "93.9%") and the crystal's entities (so the graph is
 * searchable too, which is the part that makes this more than a page find).
 *
 * No library. A few hundred entries scored by substring and field weight is
 * faster than shipping a search engine, and it is honest about what it does.
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

/** Section → the page and anchor it lives at. */
const PAGES = [
  { file: 'src/pages/index.astro',              url: '',                    page: 'Overview' },
  { file: 'src/pages/systems.astro',            url: 'systems/',            page: 'Systems' },
  { file: 'src/pages/research/index.astro',     url: 'research/',           page: 'Research' },
  { file: 'src/pages/credentials/index.astro',  url: 'credentials/',        page: 'Credentials' },
  { file: 'src/pages/crystal.astro',            url: 'crystal/',            page: 'The crystal' },
];

const strip = (s) => s
  .replace(/<[^>]+>/g, ' ')
  .replace(/\{[^{}]*\}/g, ' ')
  .replace(/&nbsp;/g, ' ')
  .replace(/&amp;/g, '&')
  .replace(/\s+/g, ' ')
  .trim();

const entries = [];

for (const { file, url, page } of PAGES) {
  let src;
  try { src = readFileSync(join(root, file), 'utf8'); } catch { continue; }

  // Section headings carry an id we can jump to.
  for (const m of src.matchAll(/id="([a-z-]+)"[\s\S]{0,400}?title="([^"]+)"/g)) {
    entries.push({ t: m[2], u: `${url}#${m[1]}`, p: page, k: 'section', s: '' });
  }

  // Prose: paragraphs long enough to be worth finding.
  for (const m of src.matchAll(/<p[^>]*>([\s\S]{60,600}?)<\/p>/g)) {
    const text = strip(m[1]);
    if (text.length < 60 || text.includes('=>')) continue;
    entries.push({ t: text.slice(0, 90), u: url, p: page, k: 'text', s: text.slice(0, 260) });
  }
}

// Research papers: their own headings, which is where the substance is.
const researchDir = join(root, 'src/content/research');
const PAPER_TITLES = {
  rules: 'Measuring whether behavioural rules change model decisions',
  spatial: 'Where a node sits should mean something',
  engineering: 'AI engineering — systems, decisions, and what they cost',
};
for (const f of readdirSync(researchDir)) {
  if (!f.endsWith('.md')) continue;
  const slug = f.replace(/\.md$/, '');
  const md = readFileSync(join(researchDir, f), 'utf8');
  entries.push({ t: PAPER_TITLES[slug] ?? slug, u: `research/${slug}/`, p: 'Research', k: 'paper', s: '' });

  for (const m of md.matchAll(/^#{2,3} (.+)$/gm)) {
    const heading = m[1].replace(/[*_`]/g, '').trim();
    const slugified = heading.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
    entries.push({ t: heading, u: `research/${slug}/#${slugified}`, p: PAPER_TITLES[slug] ?? slug, k: 'section', s: '' });
  }
  // Bold claims in the papers are usually the findings.
  for (const m of md.matchAll(/\*\*([^*]{25,120})\*\*/g)) {
    entries.push({ t: m[1].trim(), u: `research/${slug}/`, p: PAPER_TITLES[slug] ?? slug, k: 'finding', s: '' });
  }
}

// Graph entities, so searching "Qdrant" lands on the crystal rather than nowhere.
const crystal = readFileSync(join(root, 'src/data/crystal.ts'), 'utf8');
const nodesJson = crystal.slice(crystal.indexOf('export const nodes'));
for (const m of nodesJson.matchAll(/"name": "([^"]+)",\s*"type": "([^"]+)",\s*"description": "([^"]*)"/g)) {
  entries.push({ t: m[1], u: 'crystal/', p: `Knowledge graph · ${m[2]}`, k: 'entity', s: m[3].slice(0, 200) });
}

// De-duplicate on title+url; the same phrase can appear in several passes.
const seen = new Set();
const unique = entries.filter((e) => {
  const key = `${e.t}|${e.u}`;
  if (seen.has(key) || e.t.length < 4) return false;
  seen.add(key);
  return true;
});

const out = `/**
 * Search index, generated by scripts/build-search.mjs from the site's own pages,
 * the research markdown, and the crystal's entities. Do not edit by hand.
 *
 * ${unique.length} entries, captured ${new Date().toISOString().slice(0, 10)}.
 */
export interface SearchEntry {
  /** title */      t: string;
  /** url, relative to base */ u: string;
  /** where it lives */ p: string;
  /** kind */       k: 'section' | 'text' | 'paper' | 'finding' | 'entity';
  /** snippet */    s: string;
}

export const searchIndex: SearchEntry[] = ${JSON.stringify(unique)};
`;

writeFileSync(join(root, 'src/data/search.ts'), out);
const byKind = unique.reduce((a, e) => ({ ...a, [e.k]: (a[e.k] ?? 0) + 1 }), {});
console.log(`✓ search: ${unique.length} entries →`, byKind);
