#!/usr/bin/env node
/**
 * Re-read every figure on this site from the live stores and rewrite
 * src/data/hive.ts. Run it before a deploy so the numbers are never stale.
 *
 *   node scripts/pull-stats.mjs          # writes the file
 *   node scripts/pull-stats.mjs --check  # exits 1 if the file is out of date
 *
 * Requires Postgres on :5432 and Qdrant on :6333 — the same hosts the hive runs
 * on. If either is down the script fails loudly rather than writing partial data;
 * a stats file that silently keeps half its old numbers is worse than no file.
 */

import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const run = promisify(execFile);
const here = dirname(fileURLToPath(import.meta.url));
const target = join(here, '..', 'src', 'data', 'hive.ts');

const COLLECTIONS = ['sessions', 'project_context', 'knowledge', 'planning', 'code', 'docs', 'memory'];
const LABELS = { project_context: 'project ctx' };

async function psql(sql) {
  const { stdout } = await run('psql', ['-U', 'postgres', '-d', 'team_brain', '-tA', '-F', '|', '-c', sql]);
  return stdout.trim().split('\n').filter(Boolean).map((r) => r.split('|'));
}

async function qdrantCount(collection) {
  const res = await fetch(`http://localhost:6333/collections/hive_${collection}`);
  if (!res.ok) throw new Error(`qdrant hive_${collection}: HTTP ${res.status}`);
  const body = await res.json();
  const n = body?.result?.points_count;
  if (typeof n !== 'number') throw new Error(`qdrant hive_${collection}: no points_count in response`);
  return n;
}

const rows = (pairs) => Object.fromEntries(pairs.map(([k, v]) => [k, Number(v)]));

async function collect() {
  const counts = rows(await psql(`
    SELECT 'kg_e', count(*) FROM kg_entities
    UNION ALL SELECT 'kg_r', count(*) FROM kg_relationships
    UNION ALL SELECT 'code_e', count(*) FROM code_entities
    UNION ALL SELECT 'code_r', count(*) FROM code_relationships
    UNION ALL SELECT 'doc_e', count(*) FROM doc_entities
    UNION ALL SELECT 'lp_n', count(*) FROM lp_nodes
    UNION ALL SELECT 'lp_e', count(*) FROM lp_edges
    UNION ALL SELECT 'rules', count(*) FROM rules
    UNION ALL SELECT 'triggers', count(*) FROM rule_triggers
    UNION ALL SELECT 'projects', count(DISTINCT project_key) FROM lp_nodes
  `));

  const byType = (await psql(
    `SELECT entity_type, count(*) FROM kg_entities GROUP BY entity_type ORDER BY count(*) DESC`
  )).map(([type, n]) => ({ type, n: Number(n) }));

  const qdrant = [];
  for (const c of COLLECTIONS) qdrant.push({ name: LABELS[c] ?? c, points: await qdrantCount(c) });
  qdrant.sort((a, b) => b.points - a.points);

  return { counts, byType, qdrant };
}

function render({ counts, byType, qdrant }) {
  const today = new Date().toISOString().slice(0, 10);
  const pick = (t) => byType.find((r) => r.type === t)?.n ?? 0;
  const existing = readFileSync(target, 'utf8');

  // Team Brain figures are historical — that system is handed over and its
  // database is not ours to query. Carry the block through verbatim.
  const teamBrainBlock = existing.slice(existing.indexOf('/** Team Brain'));

  return `/**
 * Live counts from the hive's own stores, captured ${today}.
 *
 * Source of truth for every number rendered on this site. Generated by
 * scripts/pull-stats.mjs — do not edit by hand; run the script instead.
 */

export const capturedAt = '${today}';

export const qdrant = [
${qdrant.map((c) => `  { name: '${c.name}',${' '.repeat(Math.max(0, 12 - c.name.length))} points: ${c.points} },`).join('\n')}
] as const;

export const qdrantTotal = qdrant.reduce((n, c) => n + c.points, 0); // ${qdrant.reduce((n, c) => n + c.points, 0).toLocaleString('en-US')}

export const graphs = {
  knowledge: { entities: ${counts.kg_e}, relationships: ${counts.kg_r} },
  code:      { entities: ${counts.code_e}, relationships: ${counts.code_r} },
  docs:      { entities: ${counts.doc_e} },
  plan:      { nodes: ${counts.lp_n}, edges: ${counts.lp_e}, projects: ${counts.projects} },
} as const;

export const kgByType = [
  { type: 'concepts',   n: ${pick('concept')} },
  { type: 'lessons',    n: ${pick('lesson')} },
  { type: 'decisions',  n: ${pick('decision')} },
  { type: 'technology', n: ${pick('technology')} },
  { type: 'projects',   n: ${pick('project')} },
] as const;

export const rules = { rules: ${counts.rules}, triggers: ${counts.triggers} } as const;

export const machine = {
  ram: '24 GB',
  model: 'Gemma-4 12B Q5_K_M',
  resident: '7.7 GB',
  note: 'One Apple M4 Mac mini. No cloud inference.',
} as const;

${teamBrainBlock}`;
}

const out = render(await collect());

if (process.argv.includes('--check')) {
  const current = readFileSync(target, 'utf8');
  // Compare everything except the capture date, which moves every day.
  const strip = (s) => s.replace(/captured \d{4}-\d{2}-\d{2}/, '').replace(/capturedAt = '[^']+'/, '');
  if (strip(current) !== strip(out)) {
    console.error('✗ src/data/hive.ts is out of date — run: node scripts/pull-stats.mjs');
    process.exit(1);
  }
  console.log('✓ stats are current');
} else {
  writeFileSync(target, out);
  console.log(`✓ wrote src/data/hive.ts — ${out.split('\n').length} lines`);
}
