#!/usr/bin/env node
/**
 * Build the static crystal: the knowledge-graph entities this CV actually talks
 * about, with their real degree, tier and cluster, plus the edges between them.
 *
 *   node scripts/pull-crystal.mjs
 *
 * Why a generator and not a live query: the page is a static file on a CDN and
 * has no database behind it. The structure is real, taken from Postgres at build
 * time; what it cannot be is live. That distinction is stated on the page.
 *
 * Selection rule: an entity is included if it is CORE or MAJOR (server-computed
 * degree percentiles) AND its name appears in the CV's own source. That keeps
 * the crystal honest — it shows the part of the graph this document stands on,
 * not a flattering slice of the whole thing.
 */

import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const run = promisify(execFile);
const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const target = join(root, 'src', 'data', 'crystal.ts');

const SEP = '~|~'; // entity names contain spaces; this string does not appear in them.

const psql = async (sql) => {
  const { stdout } = await run('psql',
    ['-U', 'postgres', '-d', 'team_brain', '-tA', '-F', SEP, '-c', sql]);
  return stdout.trim().split('\n').filter(Boolean).map((r) => r.split(SEP));
};

/** Everything the CV and its papers say, as one lowercase haystack. */
function cvText() {
  const parts = [];
  const walk = (dir) => {
    for (const e of readdirSync(dir, { withFileTypes: true })) {
      const p = join(dir, e.name);
      if (e.isDirectory()) walk(p);
      else if (/\.(astro|ts|md)$/.test(e.name)) parts.push(readFileSync(p, 'utf8'));
    }
  };
  walk(join(root, 'src'));
  return parts.join('\n').toLowerCase();
}

const TIER_NAMES = ['CORE', 'MAJOR', 'MINOR', 'PERIPHERAL', 'ISOLATED'];

/** Graph name → the words the CV actually uses for the same thing. */
const ALIASES = {
  'Factorium Symbiosis': ['Factorium'],
  'The Integrator': ['Michal', 'the human'],
  'Una': ['the local model', 'local model', 'Gemma-4'],
  'LIP': ['living plan', 'plan graph', 'Living Implementation Plan'],
  'NOUS': ['harness'],
  'Codex Symbiosis': ['Codex'],
  'Apache AGE': ['Apache AGE', 'AGE'],
  'Anthropic API': ['Claude API'],
  'Barycentrum': ['barycentre'],
};

const rows = await psql(`
  SELECT e.id, regexp_replace(e.name, '[\r\n]+', ' ', 'g') AS name, e.entity_type,
         regexp_replace(COALESCE(e.description, ''), '[\r\n]+', ' ', 'g') AS description,
         e.importance_tier, e.cluster_id,
         COALESCE((SELECT count(*) FROM kg_relationships r
                   WHERE r.source_id = e.id OR r.target_id = e.id), 0) AS deg
  FROM kg_entities e
  WHERE e.importance_tier IS NOT NULL AND e.importance_tier <= 2
  ORDER BY deg DESC
`);

const haystack = cvText();
const mentioned = rows
  .map(([id, name, type, description, tier, cluster, deg]) => ({
    id: Number(id), name, type,
    // Long descriptions belong in the graph, not in a page bundle.
    description: (description || '').slice(0, 400),
    tier: Number(tier), cluster: Number(cluster), deg: Number(deg),
  }))
  // Some entities are referred to on the page by a different phrase than their
  // graph name — the page says "the local model", the graph says "Una". Map
  // those explicitly rather than pretending the text match caught them.
  .map((e) => ({ ...e, alias: ALIASES[e.name] }))
  // A short name would match half the page by accident; require 4+ characters
  // and a whole-word hit rather than a substring.
  .filter((e) => {
    const terms = [e.name, ...(e.alias ?? [])].filter((t) => t.length >= 4);
    return terms.some((t) =>
      new RegExp(`\\b${t.toLowerCase().replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`).test(haystack));
  })
  .filter((e) => Number.isFinite(e.id) && Number.isFinite(e.deg))
  // The alias was only ever a filter input; it is not part of the shape.
  .map(({ alias, ...e }) => e)
  .slice(0, 60);

const ids = new Set(mentioned.map((e) => e.id));
const edgeRows = ids.size
  ? await psql(`SELECT source_id, target_id, rel_type FROM kg_relationships
                WHERE source_id IN (${[...ids].join(',')}) AND target_id IN (${[...ids].join(',')})`)
  : [];

const edges = edgeRows
  .map(([s, t, rel]) => ({ s: Number(s), t: Number(t), rel }))
  .filter((e) => e.s !== e.t);

const out = `/**
 * The crystal: knowledge-graph entities this CV talks about, with their real
 * degree, tier and cluster taken from Postgres at build time.
 *
 * Generated by scripts/pull-crystal.mjs — do not edit by hand.
 * Captured ${new Date().toISOString().slice(0, 10)}.
 */

export const TIER_NAMES = ${JSON.stringify(TIER_NAMES)} as const;

export interface CrystalNode {
  id: number; name: string; type: string; description: string;
  tier: number; cluster: number; deg: number;
}

export const nodes: CrystalNode[] = ${JSON.stringify(mentioned, null, 2)};

export const edges: { s: number; t: number; rel: string }[] = ${JSON.stringify(edges)};

export const crystalStats = {
  nodes: ${mentioned.length},
  edges: ${edges.length},
  capturedAt: '${new Date().toISOString().slice(0, 10)}',
  /** Totals for the whole graph, so the page can say what fraction it shows. */
  graphEntities: ${rows.length},
} as const;
`;

writeFileSync(target, out);
console.log(`✓ crystal: ${mentioned.length} nodes, ${edges.length} edges → src/data/crystal.ts`);
console.log(`  top: ${mentioned.slice(0, 8).map((n) => n.name).join(' · ')}`);
