/**
 * The crystal: knowledge-graph entities this CV talks about, with their real
 * degree, tier and cluster taken from Postgres at build time.
 *
 * Generated by scripts/pull-crystal.mjs — do not edit by hand.
 * Captured 2026-08-17.
 */

export const TIER_NAMES = ["CORE","MAJOR","MINOR","PERIPHERAL","ISOLATED"] as const;

export interface CrystalNode {
  id: number; name: string; type: string;
  tier: number; cluster: number; deg: number;
}

export const nodes: CrystalNode[] = [
  {
    "id": 472,
    "name": "Hive",
    "type": "concept",
    "tier": 0,
    "cluster": 0,
    "deg": 499
  },
  {
    "id": 1,
    "name": "Factorium Symbiosis",
    "type": "project",
    "tier": 0,
    "cluster": 0,
    "deg": 497
  },
  {
    "id": 29,
    "name": "The Integrator",
    "type": "person",
    "tier": 0,
    "cluster": 0,
    "deg": 471
  },
  {
    "id": 471,
    "name": "LIP",
    "type": "concept",
    "tier": 0,
    "cluster": 0,
    "deg": 407
  },
  {
    "id": 469,
    "name": "Una",
    "type": "concept",
    "tier": 0,
    "cluster": 0,
    "deg": 370
  },
  {
    "id": 17,
    "name": "Claude",
    "type": "technology",
    "tier": 0,
    "cluster": 0,
    "deg": 351
  },
  {
    "id": 18,
    "name": "Gemma",
    "type": "technology",
    "tier": 0,
    "cluster": 0,
    "deg": 325
  },
  {
    "id": 4,
    "name": "Team Brain",
    "type": "project",
    "tier": 0,
    "cluster": 0,
    "deg": 297
  },
  {
    "id": 442,
    "name": "Qdrant",
    "type": "technology",
    "tier": 0,
    "cluster": 0,
    "deg": 167
  },
  {
    "id": 14,
    "name": "llama.cpp",
    "type": "technology",
    "tier": 0,
    "cluster": 0,
    "deg": 115
  },
  {
    "id": 21,
    "name": "React",
    "type": "technology",
    "tier": 0,
    "cluster": 0,
    "deg": 109
  },
  {
    "id": 470,
    "name": "NOUS",
    "type": "concept",
    "tier": 1,
    "cluster": 0,
    "deg": 109
  },
  {
    "id": 16,
    "name": "Anthropic API",
    "type": "technology",
    "tier": 0,
    "cluster": 0,
    "deg": 101
  },
  {
    "id": 13,
    "name": "pgvector",
    "type": "technology",
    "tier": 0,
    "cluster": 0,
    "deg": 85
  },
  {
    "id": 20,
    "name": "Astro",
    "type": "technology",
    "tier": 0,
    "cluster": 0,
    "deg": 82
  },
  {
    "id": 23,
    "name": "TypeScript",
    "type": "technology",
    "tier": 1,
    "cluster": 0,
    "deg": 80
  },
  {
    "id": 12,
    "name": "PostgreSQL",
    "type": "technology",
    "tier": 1,
    "cluster": 0,
    "deg": 64
  },
  {
    "id": 37,
    "name": "Knowledge Graph",
    "type": "concept",
    "tier": 2,
    "cluster": 0,
    "deg": 58
  },
  {
    "id": 457,
    "name": "Apache AGE",
    "type": "technology",
    "tier": 1,
    "cluster": 0,
    "deg": 58
  },
  {
    "id": 27,
    "name": "TimescaleDB",
    "type": "technology",
    "tier": 1,
    "cluster": 0,
    "deg": 35
  },
  {
    "id": 3,
    "name": "Harness",
    "type": "project",
    "tier": 0,
    "cluster": 0,
    "deg": 31
  },
  {
    "id": 11,
    "name": "ChromaDB",
    "type": "technology",
    "tier": 0,
    "cluster": 0,
    "deg": 29
  },
  {
    "id": 41,
    "name": "MEMORY",
    "type": "concept",
    "tier": 1,
    "cluster": 0,
    "deg": 18
  }
];

export const edges: { s: number; t: number; rel: string }[] = [{"s":1,"t":23,"rel":"uses"},{"s":1,"t":21,"rel":"uses"},{"s":1,"t":472,"rel":"uses"},{"s":1,"t":471,"rel":"contains"},{"s":1,"t":470,"rel":"contains"},{"s":1,"t":469,"rel":"contains"},{"s":1,"t":442,"rel":"uses"},{"s":1,"t":12,"rel":"uses"},{"s":1,"t":472,"rel":"relates_to"},{"s":1,"t":471,"rel":"relates_to"},{"s":1,"t":470,"rel":"relates_to"},{"s":1,"t":29,"rel":"created_by"},{"s":1,"t":16,"rel":"uses"},{"s":1,"t":11,"rel":"uses"},{"s":1,"t":14,"rel":"uses"},{"s":1,"t":3,"rel":"relates_to"},{"s":1,"t":4,"rel":"relates_to"},{"s":1,"t":17,"rel":"uses"},{"s":4,"t":20,"rel":"uses"},{"s":4,"t":12,"rel":"uses"},{"s":4,"t":27,"rel":"uses"},{"s":4,"t":442,"rel":"uses"},{"s":29,"t":1,"rel":"created_by"},{"s":29,"t":4,"rel":"created_by"},{"s":37,"t":12,"rel":"uses"},{"s":37,"t":13,"rel":"uses"},{"s":37,"t":11,"rel":"relates_to"},{"s":37,"t":457,"rel":"uses"},{"s":41,"t":17,"rel":"uses"},{"s":41,"t":4,"rel":"relates_to"},{"s":41,"t":11,"rel":"uses"},{"s":41,"t":1,"rel":"relates_to"},{"s":41,"t":20,"rel":"uses"},{"s":41,"t":23,"rel":"uses"},{"s":41,"t":29,"rel":"created_by"},{"s":41,"t":18,"rel":"uses"},{"s":41,"t":21,"rel":"uses"},{"s":41,"t":12,"rel":"uses"},{"s":469,"t":14,"rel":"runs_on"},{"s":470,"t":469,"rel":"governs"},{"s":471,"t":12,"rel":"uses"},{"s":472,"t":442,"rel":"uses"}];

export const crystalStats = {
  nodes: 23,
  edges: 42,
  capturedAt: '2026-08-17',
  /** Totals for the whole graph, so the page can say what fraction it shows. */
  graphEntities: 207,
} as const;
