/**
 * Live counts from the hive's own stores, captured 2026-08-14.
 *
 * Source of truth for every number rendered on this site. Generated by
 * scripts/pull-stats.mjs — do not edit by hand; run the script instead.
 */

export const capturedAt = '2026-08-14';

export const qdrant = [
  { name: 'sessions',     points: 10262 },
  { name: 'project ctx',  points: 5802 },
  { name: 'knowledge',    points: 5132 },
  { name: 'planning',     points: 3443 },
  { name: 'code',         points: 3086 },
  { name: 'docs',         points: 1166 },
  { name: 'memory',       points: 1103 },
] as const;

export const qdrantTotal = qdrant.reduce((n, c) => n + c.points, 0); // 29,994

export const graphs = {
  knowledge: { entities: 1034, relationships: 5407 },
  code:      { entities: 3086, relationships: 10209 },
  docs:      { entities: 637 },
  plan:      { nodes: 977, edges: 584, projects: 14 },
} as const;

export const kgByType = [
  { type: 'concepts',   n: 608 },
  { type: 'lessons',    n: 283 },
  { type: 'decisions',  n: 106 },
  { type: 'technology', n: 24 },
  { type: 'projects',   n: 11 },
] as const;

export const rules = { rules: 16, triggers: 55 } as const;

export const machine = {
  ram: '24 GB',
  model: 'Gemma-4 12B Q5_K_M',
  resident: '7.7 GB',
  note: 'One Apple M4 Mac mini. No cloud inference.',
} as const;
