/**
 * Live counts from the hive's own stores, captured 2026-08-21.
 *
 * Source of truth for every number rendered on this site. Generated by
 * scripts/pull-stats.mjs — do not edit by hand; run the script instead.
 */

export const capturedAt = '2026-08-21';

export const qdrant = [
  { name: 'sessions',     points: 11866 },
  { name: 'project ctx',  points: 5802 },
  { name: 'knowledge',    points: 5132 },
  { name: 'planning',     points: 3450 },
  { name: 'code',         points: 3086 },
  { name: 'docs',         points: 1166 },
  { name: 'memory',       points: 839 },
] as const;

export const qdrantTotal = qdrant.reduce((n, c) => n + c.points, 0); // 31,341

export const graphs = {
  knowledge: { entities: 1040, relationships: 5419 },
  code:      { entities: 3086, relationships: 10145 },
  docs:      { entities: 637 },
  plan:      { nodes: 984, edges: 584, projects: 14 },
} as const;

export const kgByType = [
  { type: 'concepts',   n: 613 },
  { type: 'lessons',    n: 284 },
  { type: 'decisions',  n: 106 },
  { type: 'technology', n: 24 },
  { type: 'projects',   n: 11 },
] as const;

export const rules = { rules: 20, triggers: 71 } as const;

/** Most recent commits on the environment, read from git at generation time. */
export const recentWork = [
  { date: '2026-08-20', subject: "Revert maxTokens to 8192 — it was measured, and I did not check the record" },
  { date: '2026-08-20', subject: "Raise maxTokens too — a cap does not shorten an answer, it truncates one" },
  { date: '2026-08-20', subject: "Raise the local-model watchdogs — they were my numbers, not a requirement" },
  { date: '2026-08-19', subject: "memory-watcher: embed the document name with its body" },
  { date: '2026-08-19', subject: "Correct the comment that said other layers have no timestamp" },
  { date: '2026-08-19', subject: "hive_lookup: keep the layer's own similarity beside the fused rank" },
  { date: '2026-08-12', subject: "rules: rewrite one rule that the model logically talked its way around" },
  { date: '2026-08-12', subject: "rules: count what actually fires, and catch the one failure that dominates" },
  { date: '2026-08-12', subject: "voice: log each spoken exchange as text, not audio" },
  { date: '2026-08-12', subject: "voice: dictation into the composer, input language, expandable answer, reasoning" },
  { date: '2026-08-12', subject: "voice: a spoken-conversation prompt, and the project picker applies to it" },
  { date: '2026-08-12', subject: "voice: transcribe rather than answer, and let one setting decide the language" },
] as const;

export const machine = {
  ram: '24 GB',
  model: 'Gemma-4 12B Q5_K_M',
  resident: '7.7 GB',
  note: 'One Apple M4 Mac mini. No cloud inference.',
} as const;
